"use client";

import { useCallback, useEffect, useState } from "react";
import EnforcementPanel, { STATUS_LABEL, STATUS_TONE } from "@/components/EnforcementPanel";
import {
  getAgentRuns,
  getGridCells,
  runAgentDrill,
  updateRunStatus,
  type AgentRunsPage,
  type GridCellInfo,
  type RunStatus,
  type TrackedAgentRun,
} from "@/lib/api";
import { Badge, Card, CardTitle, PageHeader, PlannedNote, Skeleton, StatCard } from "@/components/ui";

export default function EnforcementPage() {
  const [cells, setCells] = useState<GridCellInfo[]>([]);
  const [runsPage, setRunsPage] = useState<AgentRunsPage | null>(null);
  const [current, setCurrent] = useState<TrackedAgentRun | null>(null);
  const [drillRunning, setDrillRunning] = useState(false);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  // Reloads the tracked, persisted run feed and keeps whichever run is
  // selected (by run_id) in sync with the freshly fetched data — used after
  // both a drill and a status transition, since the backend is the source of
  // truth for timestamps and the signal-to-dispatch aggregate.
  const refresh = useCallback((preferId?: number) => {
    return getAgentRuns("delhi-ncr", 20, 0).then((page) => {
      setRunsPage(page);
      setCurrent((prev) => {
        const keepId = preferId ?? prev?.run_id;
        const found = keepId != null ? page.runs.find((r) => r.run_id === keepId) : undefined;
        return found ?? page.runs[0] ?? null;
      });
      return page;
    });
  }, []);

  useEffect(() => {
    getGridCells().then((d) => setCells(d.cells)).catch(() => {});
    refresh().catch(() => {});
  }, [refresh]);

  const onDrill = useCallback(() => {
    setDrillRunning(true);
    // Central-Delhi cell for a realistic drill site.
    const central = cells.find((c) => c.row_idx === 27 && c.col_idx === 23);
    runAgentDrill("delhi-ncr", central?.grid_id)
      .then((d) => {
        if (!d.anomaly_found) return;
        // The drill response is untracked (no run_id) — the backend persists
        // it as an AgentRunRecord, so pull the tracked version back from the
        // paginated feed instead of using the raw response directly.
        return refresh().then((page) => {
          const match = page.runs.find((r) => r.completed_at === d.completed_at);
          if (match) setCurrent(match);
        });
      })
      .finally(() => setDrillRunning(false));
  }, [cells, refresh]);

  const onUpdateStatus = useCallback(
    (status: RunStatus, assignee?: string) => {
      if (!current) return;
      setUpdatingStatus(true);
      updateRunStatus(current.run_id, status, assignee)
        .then((updated) => refresh(updated.run_id))
        .catch(() => {})
        .finally(() => setUpdatingStatus(false));
    },
    [current, refresh]
  );

  return (
    <>
      <PageHeader
        title="Enforcement Intelligence"
        subtitle="Anomaly detection → source attribution → prioritised patrol dispatch, generated by the LangGraph agent pipeline with evidence attached to every recommendation."
      />

      {runsPage && (
        <div className="mb-4 grid gap-4 sm:grid-cols-2">
          <StatCard label="Tracked runs" value={runsPage.total} />
          <StatCard
            label="Mean signal → dispatch"
            value={
              runsPage.mean_signal_to_dispatch_minutes !== null
                ? runsPage.mean_signal_to_dispatch_minutes.toFixed(0)
                : "—"
            }
            unit={runsPage.mean_signal_to_dispatch_minutes !== null ? "min" : undefined}
            hint="Time from forecast anomaly to a dispatched inspector — the judged intervention-speed metric"
          />
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <EnforcementPanel
            run={current}
            onDrill={onDrill}
            drillRunning={drillRunning}
            onUpdateStatus={onUpdateStatus}
            updatingStatus={updatingStatus}
          />
        </div>

        <Card>
          <CardTitle>Run history</CardTitle>
          {runsPage === null ? (
            <Skeleton className="h-32" />
          ) : runsPage.runs.length === 0 ? (
            <p className="text-sm text-neutral-500">No runs recorded yet.</p>
          ) : (
            <ol className="flex flex-col gap-2">
              {runsPage.runs.map((r) => {
                const active = r.run_id === current?.run_id;
                return (
                  <li key={r.run_id}>
                    <button
                      onClick={() => setCurrent(r)}
                      aria-pressed={active}
                      className={`w-full rounded-lg border px-3 py-2 text-left text-xs outline-none transition-colors focus-visible:ring-2 focus-visible:ring-gov-500 ${
                        active
                          ? "border-gov-300 bg-gov-50 text-gov-800"
                          : "border-neutral-200 bg-neutral-50 text-neutral-600 hover:border-neutral-300"
                      }`}
                    >
                      <span className="flex flex-wrap items-center gap-1.5 font-medium text-neutral-800">
                        cell {r.alert.grid_id} · {r.alert.forecast_value.toFixed(0)} µg/m³
                        {r.alert.synthetic && <Badge tone="amber">drill</Badge>}
                        <Badge tone={STATUS_TONE[r.status]}>{STATUS_LABEL[r.status]}</Badge>
                      </span>
                      <span className="mt-0.5 block text-neutral-500">
                        {new Date(r.completed_at).toLocaleString()} ·{" "}
                        {r.attribution.source_category.replace(/_/g, " ")}
                      </span>
                    </button>
                  </li>
                );
              })}
            </ol>
          )}
        </Card>
      </div>

      <div className="mt-6">
        <PlannedNote>
          A server-generated, digitally signed evidence PDF (for formal legal filings) is
          still planned — the evidence pack above prints or saves as PDF client-side today.
        </PlannedNote>
      </div>
    </>
  );
}
