"use client";

import { useCallback, useEffect, useState } from "react";
import EnforcementPanel from "@/components/EnforcementPanel";
import {
  getGridCells,
  getRecommendations,
  runAgentDrill,
  type AgentRun,
  type GridCellInfo,
} from "@/lib/api";
import { Badge, Card, CardTitle, PageHeader, PlannedNote, Skeleton } from "@/components/ui";

export default function EnforcementPage() {
  const [cells, setCells] = useState<GridCellInfo[]>([]);
  const [runs, setRuns] = useState<AgentRun[] | null>(null);
  const [current, setCurrent] = useState<AgentRun | null>(null);
  const [drillRunning, setDrillRunning] = useState(false);

  useEffect(() => {
    getGridCells().then((d) => setCells(d.cells)).catch(() => {});
    getRecommendations()
      .then((d) => {
        setRuns(d.runs);
        if (d.runs.length > 0) setCurrent(d.runs[0]);
      })
      .catch(() => setRuns([]));
  }, []);

  const onDrill = useCallback(() => {
    setDrillRunning(true);
    // Central-Delhi cell for a realistic drill site.
    const central = cells.find((c) => c.row_idx === 27 && c.col_idx === 23);
    runAgentDrill("delhi-ncr", central?.grid_id)
      .then((d) => {
        if (d.anomaly_found) {
          setCurrent(d);
          setRuns((prev) => [d, ...(prev ?? [])]);
        }
      })
      .finally(() => setDrillRunning(false));
  }, [cells]);

  return (
    <>
      <PageHeader
        title="Enforcement Intelligence"
        subtitle="Anomaly detection → source attribution → prioritised patrol dispatch, generated by the LangGraph agent pipeline with evidence attached to every recommendation."
      />

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <EnforcementPanel run={current} onDrill={onDrill} drillRunning={drillRunning} />
        </div>

        <Card>
          <CardTitle>Run history</CardTitle>
          {runs === null ? (
            <Skeleton className="h-32" />
          ) : runs.length === 0 ? (
            <p className="text-sm text-neutral-500">No runs recorded yet.</p>
          ) : (
            <ol className="flex flex-col gap-2">
              {runs.map((r, i) => {
                const active = r === current;
                return (
                  <li key={i}>
                    <button
                      onClick={() => setCurrent(r)}
                      aria-pressed={active}
                      className={`w-full rounded-lg border px-3 py-2 text-left text-xs outline-none transition-colors focus-visible:ring-2 focus-visible:ring-gov-500 ${
                        active
                          ? "border-gov-300 bg-gov-50 text-gov-800"
                          : "border-neutral-200 bg-neutral-50 text-neutral-600 hover:border-neutral-300"
                      }`}
                    >
                      <span className="font-medium text-neutral-800">
                        cell {r.alert.grid_id} · {r.alert.forecast_value.toFixed(0)} µg/m³
                      </span>{" "}
                      {r.alert.synthetic && <Badge tone="amber">drill</Badge>}
                      <span className="mt-0.5 block text-neutral-500">
                        {new Date(r.completed_at).toLocaleString()} ·{" "}
                        {r.attribution.source_category.replace(/_/g, " ")}
                      </span>
                    </button>
                  </li>
                );
              })}
            </ol>
          )}
        </Card>
      </div>

      <div className="mt-6">
        <PlannedNote>
          Inspector assignment &amp; dispatch tracking, PDF evidence packs for legal action,
          and closure/outcome logging (to measure signal-to-intervention time, a judged
          metric) are planned.
        </PlannedNote>
      </div>
    </>
  );
}
